# -*- coding: utf-8 -*-
"""CIE-4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lcUIceKYesiwiwOMQ1-ftP3icFrOsSiK
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df=pd.read_csv('/content/Mall_Customers (1).csv')

#data pre-processing
print("first five data :",df.head())
print('Shape of the dataset :',df.shape)
print('nature of data :',df.info())
print('Summary :',df.describe())

x=df[['CustomerID','Annual Income (k$)','Age']]

#elbow method
sum_squared_distances=[]
k_values=range(1,11)

#k-means algorthim on the training dataset
for k in k_values:
  kmeans=KMeans(n_clusters=k,random_state=42)
  kmeans.fit(x)
  sum_squared_distances.append(kmeans.inertia_)

#Visualization  of Clusters
plt.plot(k_values,sum_squared_distances,marker='o')
plt.xlabel("Number of Clusters")
plt.ylabel("Sum squared distances")
plt.title("K_means clustering")
plt.show()